language: cpp
compiler:
  - gcc
before_install:
 - sudo apt-get update
 - sudo apt-get install libgtest-dev
 - sudo apt-get install libboost-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
before_script:
 - mkdir build
 - cd build
 - cmake ..
script: make && make test
branches:
  only:
    - develop
notifications:
  recipients:
    - dang.duong@gmail.com
  email:
    on_success: change
    on_failure: always
rvm:
  - 9.00
